### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by ofirkris** [taki0112/StyleGAN-Tensorflow#2]
Hi, Thanks for helping with learning StyleGan, your code is easier to understand.
Can you share your pre-trained model?

**Comment by taki0112** [comment]
here [link](https://drive.google.com/file/d/1hLsESJujqKDKrgbNE8Nn8LAWCwglAHY3/view?usp=sharing)

**Comment by ofirkris** [comment]
Thanks so much @taki0112 
Will it work on non square images?
Will it improve quality if I train with 2500 max iterations?
