### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by ofirkris** [taki0112/StyleGAN-Tensorflow#3]
Thanks for sharing this!
I've tested with the pre-trained models, inserted them to the "checkpoint" folder
Ran this command: 
#python main.py --dataset FFHQ --img_size 1024 --progressive True --phase draw --draw uncurated --checkpoint_dir checkpoint

And got the following output + the attached results:
![stylegan](https://user-images.githubusercontent.com/9070477/61875591-a761c800-aef3-11e9-8195-b343fbf1782d.jpg)

"
Total size of variables: 26219627
Total bytes of variables: 104878508
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
 [*] Un-curated finished!
"

What am I doing wrong?
Also, how can I change the input image?

**Comment by enric1994** [comment]
I got the same output. Try running the same with `--progressive False`

**Comment by ofirkris** [comment]
Hi @enric1994 thanks, I've tried --progressive False parameter, it still doesn't work. 
I think it does not work because the loading of the checkpoint failed but I don't understand why..

**Comment by taki0112** [comment]
@ofirkris
@enric1994


`load failed` means that the checkpoint could not be called.
That is, maybe you didn't put the checkpoint file I provided into the proper path.

1. Download the checkpoint
2. unzip
3. put the checkpoint like this :
`./checkpoint/StyleGAN_FFHQ_8to1024_progressive/checkpoint`
`./checkpoint/StyleGAN_FFHQ_8to1024_progressive/StyleGAN.model-224999.data-00000-of-00001`
`./checkpoint/StyleGAN_FFHQ_8to1024_progressive/StyleGAN.model-224999.index`
`./checkpoint/StyleGAN_FFHQ_8to1024_progressive/StyleGAN.model-224999.meta`

**Comment by ofirkris** [comment]
Thanks @taki0112 !
finally - How can I change the input image?

**Comment by taki0112** [comment]
@ofirkris 
I don't understand what you mean.
What do you mean by changing the input image?

**Comment by ofirkris** [comment]
From what I understand the input images you're using are (StyleGAN.py line 642):
 src_seeds = [604, 8440, 7613, 6978, 3004]
 dst_seeds = [1336, 6968, 607, 728, 7036, 9010]

What if I want to test on my own image?

**Comment by taki0112** [comment]
If you want to your image, you need to obtain a latent vector for the image.
Please refer to [this](https://github.com/Puzer/stylegan-encoder)
